name: Print Hello, Secret, and Curl Websites  # Name of the GitHub Action

on: [push]  # Trigger the action on push events

jobs:
  print-hello-secret-curl-websites:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    env:
      URLS: ${{ secrets.URLS }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Execute Script and Save Output
      id: script-output
      run: |
        bash script.sh "$URLS"
