name: Print Hello, Secret, and Curl Google  # Name of the GitHub Action

on: [push]  # Trigger the action on push events

jobs:
  print-hello-secret-curl-google:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Print Hello, Secret, and Curl Google  # Step to print "Hello", secret variable, and curl Google
      run: |
        echo "Hello"
        echo ${{ secrets.SECRET_VARIABLE_NAME }}  # Replace SECRET_VARIABLE_NAME with the actual name of your secret variable
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://www.google.com)
        echo "Google returned HTTP status code: $RESPONSE"
