name: Print Hello, Secret, and Curl Websites  # Name of the GitHub Action

on: [push]  # Trigger the action on push events

jobs:
  print-hello-secret-curl-websites:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Print Hello, Secret, and Curl Websites  # Step to print "Hello", secret variable, and curl websites
      run: |
        echo "Hello"
        echo ${{ secrets.SECRET_VARIABLE_NAME }}  # Replace SECRET_VARIABLE_NAME with the actual name of your secret variable
        
        # Define the YAML string
        yaml_string="urls:
          - url: https://example.com
            alias: Example
            description: Example website
          - url: https://nonexistentwebsite.noway
            alias: Another Example
            description: Another example website"
        
        # Print timestamp
        timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ")
        echo "timestamp: $timestamp"
        
        # Parse YAML string and check responses
        while IFS= read -r line; do
            if [[ "$line" =~ ^\ +url:\ (.*) ]]; then
                url="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ ^\ +alias:\ (.*) ]]; then
                alias="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ ^\ +description:\ (.*) ]]; then
                description="${BASH_REMATCH[1]}"
                http_status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
                echo "- alias: $alias"
                echo "  description: $description"
                echo "  response: $http_status"
            fi
        done <<< "$yaml_string"

