name: Execute Script and Print Output

on: [push]

jobs:
  execute-script-and-print-output:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Execute Script and Save Output
      id: execute-script
      run: |
        output=$(bash script.sh "${{ secrets.SECRET_VARIABLE_NAME }}" "hello")
        echo "::set-output name=output::$output"
        
    - name: Print Output
      run: echo "Output: ${{ steps.execute-script.outputs.output }}"
