name: Rust Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: '1.55.0' # You can adjust the version as per your requirements

    - name: Build and Run Script
      run: |
        cargo build --release
        ./target/release/main
#    - name: Execute Script
#      run: bash script.sh "hello" "${{ secrets.SECRET_VARIABLE_NAME }}"
