name: Rust Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Rust
      uses: rust-build/rust-build.action@v1.4.5


    - name: Compile
      id: compile
      uses: rust-build/rust-build.action@v1.4.5
      with:
        RUSTTARGET: x86_64-unknown-linux-musl
        UPLOAD_MODE: none
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: |
          ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          ${{ steps.compile.outputs.BUILT_CHECKSUM }}
#    - name: Execute Script
#      run: bash script.sh "hello" "${{ secrets.SECRET_VARIABLE_NAME }}"
