name: Print Hello, Secret YAML File, and Curl Websites  # Name of the GitHub Action

on: [push]  # Trigger the action on push events

jobs:
  print-hello-secret-yaml-curl-websites:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Print Hello, Secret YAML File, and Curl Websites  # Step to print "Hello", secret YAML file, and curl websites
      run: |
        echo "Hello"
        # Read the secret YAML file
        secret_yaml=$(cat secret_yaml_file.yaml)

        # Parse YAML string and loop through each website URL
        for url in $(echo "$secret_yaml" | yq eval '.urls[]' -); do
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $url)
          echo "$url returned HTTP status code: $RESPONSE"
        done
