name: Concatenate Command Output to File

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  concatenate-output:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      URLS: ${{ secrets.URLS }}  # Assuming you have a secret named URLS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Script and Save Output
        id: script-output
        run: |
          mkdir -p pages/logs  # Create a directory to store output files if it doesn't exist
          bash script.sh "$URLS" >> output/output.txt
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pages/logs/output.txt
          git commit -m "Add concatenated output"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
