name: Concatenate Log

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/logger.yml'  # Trigger only when changes are made in the pages/ directory
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Define the schedule to run every hour
  schedule:
    - cron: '0 */4 * * *'

jobs:
  concatenate-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      URLS: ${{ vars.URLS }}  # Assuming you have a secret named URLS
      USER_EMAIL: "action@github.com"
      USER_NAME: "GitHub Action"
      COMMIT_MESSAGE: "Add concatenated log"
      START_DATE: "2024-04-2"  # Start date as an environment variable
      LOG_PATH: "pages/logs/"  # Calculating the unique identifier in the file name
      LOG_NAME: "log_"  # Calculating the unique identifier in the file name
      LOG_TYPE: ".yml"  # Calculating the unique identifier in the file name
      LOG_MANIFEST: "latest.txt"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Calculate Unified Log Path
        id: calculate-log-path
        run: |
          # Convert the hardcoded date to Unix time
          HARDCODED_TIME=$(date -d "$START_DATE" +%s)
          echo "HARDCODED_TIME $HARDCODED_TIME"
          # Get the current Unix time
          CURRENT_TIME=$(date +%s)
          echo "CURRENT_TIME $CURRENT_TIME"
          # Calculate the number of weeks
          LOG_WEEK=$(( (CURRENT_TIME - HARDCODED_TIME) / (60 * 60 * 24 * 7) ))
          echo "LOG_WEEK SINCE $(( (CURRENT_TIME - HARDCODED_TIME) ))"
          # Construct the log file path
          echo "LOG_WEEK=${LOG_WEEK}" >> $GITHUB_ENV
          LOG_FULL_PATH="${LOG_PATH}${LOG_NAME}${LOG_WEEK}${LOG_TYPE}"
          LOG_FULL_PATH_MANIFEST="${LOG_PATH}${LOG_MANIFEST}"
          # Output the log file path
          echo "LOG_FULL_PATH=${LOG_FULL_PATH}" >> $GITHUB_ENV
          echo "LOG_FULL_PATH_MANIFEST=${LOG_FULL_PATH_MANIFEST}" >> $GITHUB_ENV
          echo "Unified Log Path: $LOG_FULL_PATH"
          echo "Unified Log Manigest: $LOG_FULL_PATH_MANIFEST"

      

      - name: Execute Script and Save Output
        id: script-output
        run: |
          mkdir -p $LOG_PATH  # Create a directory to store output files if it doesn't exist
          bash script.sh "$URLS" >> $LOG_FULL_PATH
          # Print variables as YAML into LOG_FULL_PATH_MANIFEST file
          echo "LOG_FULL_PATH: \"$LOG_FULL_PATH\"" > $LOG_FULL_PATH_MANIFEST
          echo "LOG_REPO: \"${{ github.repository }}\"" >> $LOG_FULL_PATH_MANIFEST
          echo "LOG_BRNC: \"${GITHUB_REF##*/}\"" >> $LOG_FULL_PATH_MANIFEST
          echo "LOG_PATH: \"$LOG_PATH\"" >> $LOG_FULL_PATH_MANIFEST
          echo "LOG_NAME: \"$LOG_NAME\"" >> $LOG_FULL_PATH_MANIFEST
          echo "LOG_WEEK: \"$LOG_WEEK\"" >> $LOG_FULL_PATH_MANIFEST
          echo "LOG_TYPE: \"$LOG_TYPE\"" >> $LOG_FULL_PATH_MANIFEST
          
      - name: Commit Changes
        run: |
          git config --local user.email "${USER_EMAIL}"
          git config --local user.name "${USER_NAME}"
          git add $LOG_FULL_PATH
          git add $LOG_FULL_PATH_MANIFEST
          git commit -m "${COMMIT_MESSAGE}"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
