name: Concatenate Log

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/logger.yml'  # Trigger only when changes are made in the pages/ directory
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  concatenate-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      URLS: ${{ secrets.URLS }}  # Assuming you have a secret named URLS
      USER_EMAIL: "action@github.com"
      USER_NAME: "GitHub Action"
      COMMIT_MESSAGE: "Add concatenated log"
      LOG_PATH: "pages/logs/"  # Calculating the unique identifier in the file name
      LOG_FILE: "log_$(date +%s).yml"  # Calculating the unique identifier in the file name

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute Script and Save Output
        id: script-output
        run: |
          mkdir -p $LOG_PATH  # Create a directory to store output files if it doesn't exist
          bash script.sh "$URLS" >> $LOG_PATH$LOG_FILE
          
      - name: Commit Changes
        run: |
          git config --local user.email "${{ env.USER_EMAIL }}"
          git config --local user.name "${{ env.USER_NAME }}"
          git add $LOG_PATH$LOG_FILE
          git commit -m "${{ env.COMMIT_MESSAGE }}"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
