name: Concatenate Log

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/logger.yml'  # Trigger only when changes are made in the pages/ directory
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  concatenate-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      URLS: ${{ secrets.URLS }}  # Assuming you have a secret named URLS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute Script and Save Output
        id: script-output
        run: |
          mkdir -p pages/logs  # Create a directory to store output files if it doesn't exist
          bash script.sh "$URLS" >> pages/logs/log.txt
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pages/logs/log.txt
          git commit -m "Add concatenated log"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
