name: Concatenate Log

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/logger.yml'  # Trigger only when changes are made in the pages/ directory
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  concatenate-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      URLS: ${{ secrets.URLS }}  # Assuming you have a secret named URLS
      USER_EMAIL: "action@github.com"
      USER_NAME: "GitHub Action"
      COMMIT_MESSAGE: "Add concatenated log"
      START_DATE: "2024-04-10"  # Start date as an environment variable
      LOG_PATH: "pages/logs/"  # Calculating the unique identifier in the file name
      LOG_FILE: "log_"  # Calculating the unique identifier in the file name
      LOG_FORM: ".yml"  # Calculating the unique identifier in the file name

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Calculate Unified Log Path
        id: calculate-log-path
        run: |
          START_UNIX_TIME=$(date -d "${START_DATE}" +%s)  # Get the Unix time for the start date
          CURRENT_TIME=$(date +%s)  # Get the current Unix time
          SECONDS_SINCE_START=$((CURRENT_TIME - START_UNIX_TIME))  # Calculate seconds since the start date
          LOG_FULL_PATH="${LOG_PATH}${LOG_FILE}${SECONDS_SINCE_START}${LOG_FORM}"
          echo "LOG_FULL_PATH=${LOG_FULL_PATH}" >> $GITHUB_ENV
          echo "Unified Log Path: $LOG_FULL_PATH"
      

      - name: Execute Script and Save Output
        id: script-output
        run: |
          mkdir -p $LOG_PATH  # Create a directory to store output files if it doesn't exist
          bash script.sh "$URLS" >> $LOG_FULL_PATH
          
      - name: Commit Changes
        run: |
          git config --local user.email "${USER_EMAIL}"
          git config --local user.name "${USER_NAME}"
          git add $LOG_FULL_PATH
          git commit -m "${COMMIT_MESSAGE}"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    